var img;
var arrowAway;
var arrowTowards;
var arrowRight;
var arrowLeft;
var arrowDown;
var arrowUp;
var n0;
var n1;
var n2;
var n3;
var n4;
var n5;
var n6;
var n7;
var n8;
var n9;
var d0;
var d1;
var d2;
var d3;
var d4;
var d5;
var d6;
var d7;
var d8;
var d9;
var right;
var wrong;
var A;
var B;
var C;
var D;
var ASL;
var q1, q2, q3, q4;

function setup() {
    createCanvas(window.innerWidth,window.innerHeight);
    img = loadImage('https://i.imgur.com/xlgHoq9.jpg');
    arrowAway = loadImage('https://i.imgur.com/ArRz2qu.jpg');
    arrowTowards  = loadImage('https://i.imgur.com/jemJrwT.jpg');
    arrowRight = loadImage('https://i.imgur.com/Yy9SwoG.jpg');
    arrowLeft = loadImage('https://i.imgur.com/YFXuaXu.jpg');
    arrowDown = loadImage('https://i.imgur.com/6gNfGbL.jpg');
    arrowUp = loadImage('https://i.imgur.com/7MedbAa.jpg');
    n0 = loadImage('https://i.imgur.com/OzbNmdk.png');
    n1 = loadImage('https://i.imgur.com/FjkAssp.png');
    n2 = loadImage('https://i.imgur.com/BXG9Zs7.png');
    n3 = loadImage('https://i.imgur.com/n1GjXjQ.png');
    n4 = loadImage('https://i.imgur.com/5bfPRkh.png');
    n5 = loadImage('https://i.imgur.com/NNsqR9L.png');
    n6 = loadImage('https://i.imgur.com/FfC58OZ.png');
    n7 = loadImage('https://i.imgur.com/584BI6a.png');
    n8 = loadImage('https://i.imgur.com/oRvjudV.png');
    n9 = loadImage('https://i.imgur.com/Uko99bk.png');
    d0 = loadImage('https://i.imgur.com/ah3LVXv.png');
    d1 = loadImage('https://i.imgur.com/AIgdzrq.png');
    d2 = loadImage('https://i.imgur.com/hUM6hXN.png');
    d3 = loadImage('https://i.imgur.com/SDw5BWZ.png');
    d4 = loadImage('https://i.imgur.com/kCFgMqB.png');
    d5 = loadImage('https://i.imgur.com/W5TeTiM.png');
    d6 = loadImage('https://i.imgur.com/BGHPTAw.png');
    d7 = loadImage('https://i.imgur.com/Is1yHuR.png');
    d8 = loadImage('https://i.imgur.com/skSB8Eo.png');
    d9 = loadImage('https://i.imgur.com/RL5NQsC.png');
    right = loadImage('https://i.imgur.com/2S3wxvr.png');
    wrong = loadImage('https://i.imgur.com/rYwGBvq.png');
    // FINAL PROJECT A to D
    A = loadImage('https://i.imgur.com/a98o8FP.png');
    B = loadImage('https://i.imgur.com/nbQp1Dt.png');
    C = loadImage('https://i.imgur.com/DkUDPfg.png');
    D = loadImage('https://i.imgur.com/WwU6gfx.png');
    ASL = loadImage('https://i.imgur.com/QzsE7Oa.png');

    // Math question
    q1 = loadImage('https://i.imgur.com/gUeOeRu.png');
    q2 = loadImage('https://i.imgur.com/H1haQmE.jpg');
    q3 = loadImage('https://i.imgur.com/7Ro1ZOI.jpg');
    q4 = loadImage('https://i.imgur.com/Ek7YcaL.png');
}